/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import model.Musica;
import model.DaoGenerico;

/**
 *
 * @author victorferrari
 */
public class MusicasView extends javax.swing.JFrame {
    Musica musicasObject;
    DaoGenerico daoGenericoObject;
    /**
     * Creates new form VeiculoView
     */
    public MusicasView() {
        initComponents();
        daoGenericoObject = new DaoGenerico();
        this.carregaTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFiltro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        musicaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        artistasField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gravadoraField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tempoField = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        musicasTable = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        filtroField = new javax.swing.JTextField();
        btnListarTodos = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        rbtnGravadora = new javax.swing.JRadioButton();
        rbtnArtistas = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataProducaoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 32)); // NOI18N
        jLabel1.setText("Gerenciamento de Musicas");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel2.setText("Código:");

        codigoField.setEditable(false);
        codigoField.setBackground(new java.awt.Color(102, 102, 102));
        codigoField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        codigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel3.setText("Musica:");

        musicaField.setBackground(new java.awt.Color(102, 102, 102));
        musicaField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        musicaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicaFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel4.setText("Artistas:");

        artistasField.setBackground(new java.awt.Color(102, 102, 102));
        artistasField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        artistasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistasFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel5.setText("Gravadora:");

        gravadoraField.setBackground(new java.awt.Color(102, 102, 102));
        gravadoraField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        gravadoraField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravadoraFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel6.setText("Tempo:");

        tempoField.setBackground(new java.awt.Color(102, 102, 102));
        tempoField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tempoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempoFieldFocusLost(evt);
            }
        });
        tempoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoFieldActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        musicasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        musicasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicasTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(musicasTable);

        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.setToolTipText("");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnListarTodos.setText("Listar Todos");
        btnListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodosActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnGroupFiltro.add(rbtnGravadora);
        rbtnGravadora.setText("Gravadora");
        rbtnGravadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGravadoraActionPerformed(evt);
            }
        });

        btnGroupFiltro.add(rbtnArtistas);
        rbtnArtistas.setText("Artistas");

        jLabel7.setText("Filtrar Por:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel8.setText("Data de Produção:");

        dataProducaoField.setBackground(new java.awt.Color(102, 102, 102));
        dataProducaoField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dataProducaoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataProducaoFieldFocusLost(evt);
            }
        });
        dataProducaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataProducaoFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempoField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gravadoraField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(artistasField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musicaField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(322, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(251, 257, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataProducaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnGravadora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnArtistas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filtroField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(musicaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(artistasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gravadoraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tempoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dataProducaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnGravadora)
                    .addComponent(rbtnArtistas)
                    .addComponent(jLabel7))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoFieldActionPerformed

    private void musicaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicaFieldActionPerformed

    private void artistasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistasFieldActionPerformed

    private void gravadoraFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravadoraFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gravadoraFieldActionPerformed

    private void tempoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoFieldActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(musicaField.getText().equals("") || artistasField.getText().equals("") || gravadoraField.getText().equals("") || tempoField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
        
            musicasObject = new Musica();
            musicasObject.setNomeMusica(musicaField.getText());
            musicasObject.setArtistasMusica(artistasField.getText());
            musicasObject.setGravadoraMusica(gravadoraField.getText());
            musicasObject.setTempoMusica(tempoField.getText());
            musicasObject.setDataProducaoMusica(dataProducaoField.getText());

            
            //System.out.println(musicasObject.getNomeMusica() + musicasObject.getArtistasMusica() + musicasObject.getGravadoraMusica() + musicasObject.getTempoMusica() + musicasObject.getDataProducaoMusica());
            
            try {
                if(codigoField.getText().equals("")){
                daoGenericoObject.inserir(musicasObject);
            } else {
                musicasObject.setIdMusica(Integer.parseInt(codigoField.getText()));
                daoGenericoObject.alterar(musicasObject, "idMusica", musicasObject.getIdMusica());
            }
            } catch (Exception e) {
                System.out.println(e);
            }
            
            
            
            this.limparCampos();
            this.carregaTable();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tempoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempoFieldFocusLost
//        try {
//            int i = Integer.parseInt(tempoField.getText());
//        } catch (NumberFormatException e) {
//            System.out.println("e");
//            tempoField.setText("");
//        }
    }//GEN-LAST:event_tempoFieldFocusLost

    private void musicasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicasTableMouseClicked
        codigoField.setText(musicasTable.getValueAt(musicasTable.getSelectedRow(), MusicasTableModel.COL_CODIGO).toString());
        musicaField.setText(musicasTable.getValueAt(musicasTable.getSelectedRow(), MusicasTableModel.COL_NOME_MUSICA).toString());
        artistasField.setText(musicasTable.getValueAt(musicasTable.getSelectedRow(), MusicasTableModel.COL_ARTISTAS_MUSICA).toString());
        gravadoraField.setText(musicasTable.getValueAt(musicasTable.getSelectedRow(), MusicasTableModel.COL_GRAVADORA_MUSICA).toString());
        tempoField.setText(musicasTable.getValueAt(musicasTable.getSelectedRow(), MusicasTableModel.COL_TEMPO_MUSICA).toString());
        dataProducaoField.setText(musicasTable.getValueAt(musicasTable.getSelectedRow(), MusicasTableModel.COL_DATA_PRODUCAO_MUSICA).toString());
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_musicasTableMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirmar Exclusão?", "Exclusão de Veículo", JOptionPane.YES_NO_OPTION);
        if(confirma == 0){
            try {
                daoGenericoObject.excluir(new Musica(), "idMusica", Integer.parseInt(codigoField.getText()));
            } catch (Exception e) {
                System.out.println(e);
            }
            
            this.limparCampos();
            this.carregaTable();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        this.limparCampos();
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodosActionPerformed
       this.limparCampos();
       this.carregaTable();
    }//GEN-LAST:event_btnListarTodosActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String campo;
        
        if(rbtnGravadora.isSelected()){
            campo = "gravadoraMusica";
        } else {
            campo = "artistasMusica";
        }
        
        try {
           musicasTable.setModel(new MusicasTableModel(daoGenericoObject.buscarTodosFiltro(new Musica(), campo, filtroField.getText()))); 
        } catch (Exception e) {
            System.out.println(e);
        }
        
        //musicasTable.setModel(new MusicasTableModel(daoVeiculoObject.listarPorFiltro(campo, filtroField.getText())));
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void dataProducaoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataProducaoFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dataProducaoFieldFocusLost

    private void dataProducaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataProducaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataProducaoFieldActionPerformed

    private void rbtnGravadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGravadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnGravadoraActionPerformed

    public void limparCampos(){
        musicaField.setText("");
        artistasField.setText("");
        gravadoraField.setText("");
        tempoField.setText("");
        dataProducaoField.setText("");
        codigoField.setText("");
}
    public void carregaTable(){
        try {
            musicasTable.setModel(new MusicasTableModel(daoGenericoObject.buscarTodos(new Musica())));
            btnExcluir.setEnabled(false);
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistasField;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.ButtonGroup btnGroupFiltro;
    private javax.swing.JButton btnListarTodos;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField codigoField;
    private javax.swing.JTextField dataProducaoField;
    private javax.swing.JTextField filtroField;
    private javax.swing.JTextField gravadoraField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField musicaField;
    private javax.swing.JTable musicasTable;
    private javax.swing.JRadioButton rbtnArtistas;
    private javax.swing.JRadioButton rbtnGravadora;
    private javax.swing.JTextField tempoField;
    // End of variables declaration//GEN-END:variables
}
